= Painground

image:https://travis-ci.org/barclay-reg/dhbw-painground.svg?branch=master[Build Status, link=https://travis-ci.org/barclay-reg/dhbw-painground]
image:https://sonarcloud.io/api/badges/gate?key=net.kleinschmager.dhbw.tfe15:painground[Quality Gate, link=https://sonarcloud.io/dashboard/index/net.kleinschmager.dhbw.tfe15:painground]

== Gruppe 1

https://github.com/fn-tfe15-2-g1/dhbw-painground

image:https://travis-ci.org/fn-tfe15-2-g1/dhbw-painground.svg?branch=master[Build Status, link=https://travis-ci.org/fn-tfe15-2-g1/dhbw-painground]
image:https://sonarcloud.io/api/badges/gate?key=net.kleinschmager.dhbw.tfe15:g1-painground[Quality Gate, link=https://sonarcloud.io/dashboard/index/net.kleinschmager.dhbw.tfe15:g1-painground]

== Gruppe 2

https://github.com/fn-tfe15-2-g2/dhbw-painground

image:https://travis-ci.org/fn-tfe15-2-g2/dhbw-painground.svg?branch=master[Build Status, link=https://travis-ci.org/fn-tfe15-2-g2/dhbw-painground]
image:https://sonarcloud.io/api/badges/gate?key=net.kleinschmager.dhbw.tfe15:g2-painground[Quality Gate, link=https://sonarcloud.io/dashboard/index/net.kleinschmager.dhbw.tfe15:g2-painground]

== Gruppe 3

https://github.com/fn-tfe15-2-g3/dhbw-painground

image:https://travis-ci.org/fn-tfe15-2-g3/dhbw-painground.svg?branch=master[Build Status, link=https://travis-ci.org/fn-tfe15-2-g3/dhbw-painground]
image:https://sonarcloud.io/api/badges/gate?key=net.kleinschmager.dhbw.tfe15:g3-painground[Quality Gate, link=https://sonarcloud.io/dashboard/index/net.kleinschmager.dhbw.tfe15:g3-painground]

== Gruppe 4

https://github.com/fn-tfe15-2-g4/dhbw-painground

image:https://travis-ci.org/fn-tfe15-2-g4/dhbw-painground.svg?branch=master[Build Status, link=https://travis-ci.org/fn-tfe15-2-g4/dhbw-painground]
image:https://sonarcloud.io/api/badges/gate?key=net.kleinschmager.dhbw.tfe15:g4-painground[Quality Gate, link=https://sonarcloud.io/dashboard/index/net.kleinschmager.dhbw.tfe15:g4-painground]

== Gruppe 5

https://github.com/fn-tfe15-2-g5/dhbw-painground

image:https://travis-ci.org/fn-tfe15-2-g5/dhbw-painground.svg?branch=master[Build Status, link=https://travis-ci.org/fn-tfe15-2-g5/dhbw-painground]
image:https://sonarcloud.io/api/badges/gate?key=net.kleinschmager.dhbw.tfe15:g5-painground[Quality Gate, link=https://sonarcloud.io/dashboard/index/net.kleinschmager.dhbw.tfe15:g5-painground]

== Gruppe 6

https://github.com/fn-tfe15-2-g6/dhbw-painground

image:https://travis-ci.org/fn-tfe15-2-g6/dhbw-painground.svg?branch=master[Build Status, link=https://travis-ci.org/fn-tfe15-2-g6/dhbw-painground]
image:https://sonarcloud.io/api/badges/gate?key=net.kleinschmager.dhbw.tfe15:g6-painground[Quality Gate, link=https://sonarcloud.io/dashboard/index/net.kleinschmager.dhbw.tfe15:g6-painground]

== Gruppe 7

https://github.com/fn-tfe15-2-g7/dhbw-painground

image:https://travis-ci.org/fn-tfe15-2-g7/dhbw-painground.svg?branch=master[Build Status, link=https://travis-ci.org/fn-tfe15-2-g7/dhbw-painground]
image:https://sonarcloud.io/api/badges/gate?key=net.kleinschmager.dhbw.tfe15:g7-painground[Quality Gate, link=https://sonarcloud.io/dashboard/index/net.kleinschmager.dhbw.tfe15:g7-painground]


= PeoplesKnowledge

=== Idea

Have an Application to manage the knowledge/skills of members withina any organisation.
One new line

=== Development

Based on Spring boot with
* H2 Database (http://www.h2database.com)
* Liquibase for DB Setup and Migration (http://liquibase.org)
* Vaadin as for WebUI (https://vaadin.com)

==== Start development

. clone repo
. run `mvn clean install` (to execute some vaadin tasks)
. run `mvn spring-boot:run` in commandline or launch class `net.kleinschmager.dhbw.tfe15.painground.PaingroundApplication` as main class
. view UI at http://localhost:8080
. You can look at http://localhost:8080/liquibase to review the list of db scripts.
. View H2 console (at http://localhost:8080/h2-console) so that you can review the state of the database (the default jdbc url is `jdbc:h2:mem:testdb`).
